cloudnativeapp/charts

submitted/hexo/.helmignore
submitted/hexo/Chart.yaml
submitted/hexo/Makefile
submitted/hexo/README.md
submitted/hexo/templates/NOTES.txt
submitted/hexo/templates/_helpers.tpl
submitted/hexo/templates/deployment.yaml
submitted/hexo/templates/ingress.yaml
submitted/hexo/templates/service.yaml
submitted/hexo/values.yaml

- 参赛队伍名称： 阿里云首席差评师
- 参赛人： @zeusro
- charts的功能：
- 只需填一个 GitHub URL + 自有域名 ,即可在 Kubernetes 上轻松部署 hexo 博客
- 参赛要求

[云原生应用大赛] hexo Chart

---

submitted/redis-operator/.helmignore
submitted/redis-operator/Chart.yaml
submitted/redis-operator/README.md
submitted/redis-operator/templates/NOTES.txt
submitted/redis-operator/templates/_functions.tpl
submitted/redis-operator/templates/crd.yaml
submitted/redis-operator/templates/deployment.yaml
submitted/redis-operator/templates/rbac.yaml
submitted/redis-operator/templates/service.yaml
submitted/redis-operator/values.yaml

- 参赛队伍名称: 万一中奖了呢
- 参赛人: @SataQiu
- Chart 功能：
支持 Redis 哨兵模式集群的 k8s 原生 Operator，基于 operator-sdk 实现
- 参赛要求：

[云原生应用大赛] Redis-Operator Chart

---

README.md

We now have recommendation from https://github.com/helm/charts#happy-helming-in-china
So let's change the title to align with it.

Update README  to align with official helm repo

---

submitted/admin-mongo/.helmignore
submitted/admin-mongo/Chart.yaml
submitted/admin-mongo/README.md
submitted/admin-mongo/templates/NOTES.txt
submitted/admin-mongo/templates/_helpers.tpl
submitted/admin-mongo/templates/deployment.yaml
submitted/admin-mongo/templates/ingress.yaml
submitted/admin-mongo/templates/service.yaml
submitted/admin-mongo/values.yaml

- 参赛队伍名称： 西二旗靓仔
- 参赛人： @TerrySolar
- charts的功能：
- MongoDB的web管理工具，类似于PHPmyadmin
- 参赛要求：

[云原生应用大赛] adminMongo Chart

---

submitted/hugo/Chart.yaml
submitted/hugo/README.md
submitted/hugo/templates/NOTES.txt
submitted/hugo/templates/_helpers.tpl
submitted/hugo/templates/configmap.yaml
submitted/hugo/templates/deployment.yaml
submitted/hugo/templates/ingress.yaml
submitted/hugo/templates/service.yaml
submitted/hugo/values.yaml

- 参赛队伍名称： 凯京科技
- 参赛人： @sunny0826
- charts的功能：
- 页面展示helloworld
- 根据传入的values显示
- 参赛要求
- [README 文档](submitted/hugo/README.md)
- 有效性验证，已使用ACK（标准版&托管版，版本：v1.12.6-aliyun.1）验证

[云原生应用大赛] Hugo Chart

---

submitted/nginx-php/.helmignore
submitted/nginx-php/Chart.yaml
submitted/nginx-php/README.md
submitted/nginx-php/templates/NOTES.txt
submitted/nginx-php/templates/_helpers.tpl
submitted/nginx-php/templates/configmap.yaml
submitted/nginx-php/templates/deployment-statefulset.yaml
submitted/nginx-php/templates/ingress.yaml
submitted/nginx-php/templates/pvc.yaml
submitted/nginx-php/templates/secret.yaml
submitted/nginx-php/templates/service-headless.yaml
submitted/nginx-php/templates/service.yaml
submitted/nginx-php/values.yaml

* 参赛队伍名称： ygqygq2
* 参赛人： @ygqygq2
* charts的功能：
* 基于1and1internet的nginx php做的chart
* 参赛要求

[云原生应用大赛] nginx-php charts

---

submitted/oneindex/.gitignore
submitted/oneindex/.helmignore
submitted/oneindex/Chart.yaml
submitted/oneindex/Readme.md
submitted/oneindex/templates/NOTES.txt
submitted/oneindex/templates/_helpers.tpl
submitted/oneindex/templates/dpl.yaml
submitted/oneindex/templates/ingress.yaml
submitted/oneindex/templates/pvc.yaml
submitted/oneindex/templates/secret.yaml
submitted/oneindex/templates/svc.yaml
submitted/oneindex/values.yaml

- 参赛队伍名称：TimeBye
- 参赛人：@TimeBye
- charts的功能：
- 安装 [oneindex](https://github.com/donwa/oneindex) 至集群中。
- Chart内镜像使用 `azk8s.cn` 加速，国内不受网络限制。
- 参赛要求
[![asciicast](https://asciinema.org/a/261340.svg)](https://asciinema.org/a/261340)

[云原生应用大赛] oneindex Chart

---

submitted/redispapa/Chart.yaml

fix Redispapa chart icon

---

submitted/skywalking/.helmignore
submitted/skywalking/Chart.yaml
submitted/skywalking/OWNERS
submitted/skywalking/README.md
submitted/skywalking/templates/NOTES.txt
submitted/skywalking/templates/_helpers.tpl
submitted/skywalking/templates/es-init.job.yaml
submitted/skywalking/templates/oap-deployment.yaml
submitted/skywalking/templates/oap-role.yaml
submitted/skywalking/templates/oap-rolebinding.yaml
submitted/skywalking/templates/oap-serviceaccount.yaml
submitted/skywalking/templates/oap-svc.yaml
submitted/skywalking/templates/ui-deployment.yaml
submitted/skywalking/templates/ui-ingress.yaml
submitted/skywalking/templates/ui-svc.yaml
submitted/skywalking/values.yaml

- 参赛队伍名称： innerpeacez
- 参赛人： @innerpeacez
- charts的功能：
skywalking 使用 chart 部署到 kubernetes
- 参赛要求

[云原生应用大赛] Skywalking

---

submitted/docker-gitlab/Chart.yaml
submitted/docker-gitlab/templates/database/database-mysql-ss.yaml
submitted/docker-gitlab/templates/database/database-postgresql-ss.yaml
submitted/docker-gitlab/templates/redis/redis-ss.yaml

[FIX] fix volume claim templates

---

submitted/arkid/.helmignore
submitted/arkid/Chart.yaml
submitted/arkid/README.md
submitted/arkid/templates/NOTES.txt
submitted/arkid/templates/_helpers.tpl
submitted/arkid/templates/cert.yaml
submitted/arkid/templates/configmap.yaml
submitted/arkid/templates/deployment-fe.yaml
submitted/arkid/templates/deployment-portal.yaml
submitted/arkid/templates/deployment.yaml
submitted/arkid/templates/hook-oneid-register.yaml
submitted/arkid/templates/ingress.yaml
submitted/arkid/templates/pvc.yaml
submitted/arkid/templates/service-fe.yaml
submitted/arkid/templates/service-portal.yaml
submitted/arkid/templates/service.yaml
submitted/arkid/templates/tests/test-connection.yaml
submitted/arkid/values.yaml

- 参赛队伍名称： [北京龙归科技](https://www.longguikeji.com/)
- 参赛人： @skoogi
- charts的功能：
- 企业单点登录解决方案，兼容各种常见协议
- 账号与分组管理
- 权限管理
- 参赛要求

[云原生应用大赛]ArkID chart

---

submitted/swagger-ui/.helmignore
submitted/swagger-ui/Chart.yaml
submitted/swagger-ui/README.md
submitted/swagger-ui/templates/NOTES.txt
submitted/swagger-ui/templates/_helpers.tpl
submitted/swagger-ui/templates/deployment.yaml
submitted/swagger-ui/templates/ingress.yaml
submitted/swagger-ui/templates/service.yaml
submitted/swagger-ui/templates/tests/test-connection.yaml
submitted/swagger-ui/values.yaml

- 参赛队伍名称： Go
- 参赛人： @gosoon
- charts的功能：
一个可视化的接口文档管理工具，用于管理多个项目的 API 接口文档
- 参赛要求

[云原生应用大赛] swagger-ui 

---

submitted/slate/.helmignore
submitted/slate/Chart.yaml
submitted/slate/README.md
submitted/slate/templates/NOTES.txt
submitted/slate/templates/_helpers.tpl
submitted/slate/templates/deployment.yaml
submitted/slate/templates/ingress.yaml
submitted/slate/templates/service.yaml
submitted/slate/values.yaml

参赛队伍名称：redhatxl
参赛人： @redhatxl
[Slate](https://spectrum.chat/slate)可帮助您创建漂亮，智能，响应灵敏的API文档。
<p align="center"><img src="https://raw.githubusercontent.com/lord/img/master/screenshot-slate.png" width=700 alt="Screenshot of Example Documentation created with Slate"></p>

[云原生应用大赛] Slate

---

submitted/storybook/.helmignore
submitted/storybook/Chart.yaml
submitted/storybook/README.md
submitted/storybook/templates/NOTES.txt
submitted/storybook/templates/_helpers.tpl
submitted/storybook/templates/deployment.yaml
submitted/storybook/templates/ingress.yaml
submitted/storybook/templates/service.yaml
submitted/storybook/values.yaml

- 参赛队伍名称： toliu
- 参赛人： @toliu
- charts的功能：用于为React/Vue/Angular开发UI组件，允许团队设计、构建和组织UI组件
- 欢迎界面展示  
- 加载项目
> 传入项目地址:  `--set source.repo=https://github.com/toliu/storybook-helm.git`

[云原生应用大赛] Storybook

---

submitted/crawlab/.helmignore
submitted/crawlab/Chart.yaml
submitted/crawlab/README.md
submitted/crawlab/requirements.lock
submitted/crawlab/requirements.yaml
submitted/crawlab/templates/NOTES.txt
submitted/crawlab/templates/_helpers.tpl
submitted/crawlab/templates/ingress.yaml
submitted/crawlab/templates/master-deployment.yaml
submitted/crawlab/templates/service.yaml
submitted/crawlab/templates/worker-deployment.yaml
submitted/crawlab/values.yaml

- 参赛队伍名称： fresh618
- 参赛人： [@fresh618](https://github.com/fresh618)
- charts的功能：
基于Golang的分布式爬虫管理平台，支持Python、NodeJS、Go、Java、PHP等多种编程语言以及多种爬虫框架。
- 部署效果验证过程
参赛要求

[云原生应用大赛] Crawlab

---

submitted/arkid/Chart.yaml

[云原生应用大赛] chore(arkid): add logo

---

submitted/kruise/.helmignore
submitted/kruise/Chart.yaml
submitted/kruise/README.md
submitted/kruise/templates/_helpers.tpl
submitted/kruise/templates/apps_v1alpha1_broadcastjob.yaml
submitted/kruise/templates/apps_v1alpha1_sidecarset.yaml
submitted/kruise/templates/apps_v1alpha1_statefulset.yaml
submitted/kruise/templates/manager.yaml
submitted/kruise/templates/rbac_role.yaml
submitted/kruise/templates/rbac_role_binding.yaml
submitted/kruise/templates/webhookconfiguration.yaml
submitted/kruise/values.yaml

- 参赛队伍名称： 周刷
- 参赛人： @hellolijj
charts的功能：
安装  [kruise](https://github.com/openkruise/kruise)
参赛要求

[云原生应用大赛] add kruise charts in apphub

---

submitted/etcd-manage/README.md

README.md文件中图片和sql使用完整url，防止脱离github无法显示图片

参赛项目 etcd-manage 图片和sql使用完整地址

---

submitted/reservation-client/.helmignore
submitted/reservation-client/Chart.yaml
submitted/reservation-client/README.md
submitted/reservation-client/templates/NOTES.txt
submitted/reservation-client/templates/_helpers.tpl
submitted/reservation-client/templates/deployment.yaml
submitted/reservation-client/templates/ingress.yaml
submitted/reservation-client/templates/service.yaml
submitted/reservation-client/values.yaml

参赛队伍名称：ActivityReservation
参赛人： @WeihanLi
charts的功能：
- 活动室/会议室 预约客户端
- 活动室预约
- 公告展示
参赛要求
-  [x] README 文档，含功能说明、安装步骤。
-  [x] 有效性验证，已使用minikube验证

[云原生应用大赛] 活动室预约客户端(reservation-client) charts

---

submitted/hasura-helm3/.helmignore
submitted/hasura-helm3/Chart.yaml
submitted/hasura-helm3/LICENSE
submitted/hasura-helm3/README.md
submitted/hasura-helm3/templates/NOTES.txt
submitted/hasura-helm3/templates/_helpers.tpl
submitted/hasura-helm3/templates/deployment.yaml
submitted/hasura-helm3/templates/ingress.yaml
submitted/hasura-helm3/templates/service.yaml
submitted/hasura-helm3/values.yaml

参赛队伍名称： 3factorapp-lover
参赛人： @delapecci
charts的功能：
安装Hasura，一个实时GraphQL引擎@Postgres
参赛要求

Submit Hasura chart (参赛)

---

submitted/confluence/.helmignore
submitted/confluence/Chart.yaml
submitted/confluence/README.md
submitted/confluence/templates/NOTES.txt
submitted/confluence/templates/_helpers.tpl
submitted/confluence/templates/deployment.yaml
submitted/confluence/templates/service.yaml
submitted/confluence/values.yaml
submitted/jira/.helmignore
submitted/jira/Chart.yaml
submitted/jira/README.md
submitted/jira/templates/NOTES.txt
submitted/jira/templates/_helpers.tpl
submitted/jira/templates/deployment.yaml
submitted/jira/templates/service.yaml
submitted/jira/values.yaml

参赛队伍名称： k8sre
参赛人： @k8sre
charts 的功能：
- 容器化部署confluence&jira工具
参赛要求
- README 文档，含功能说明、安装步骤
- 有效性验证，已使用kubernetes 集群验证

Add confluence & jira

---

submitted/reservation-client/Chart.yaml
submitted/reservation-client/README.md
submitted/reservation-client/templates/NOTES.txt
submitted/reservation-client/templates/deployment.yaml
submitted/reservation-client/templates/service.yaml
submitted/reservation-client/values.yaml

some update for helm 3 and add additional info

update reservation-client Chart

---

submitted/zookeeper-3nodes/Chart.yaml
submitted/zookeeper-3nodes/README.md
submitted/zookeeper-3nodes/templates/NOTES.txt
submitted/zookeeper-3nodes/templates/_helpers.tpl
submitted/zookeeper-3nodes/templates/service.yaml
submitted/zookeeper-3nodes/templates/statefulset-zk.yaml
submitted/zookeeper-3nodes/values.yaml

A Helm chart for three-nodes zookeeper cluster,Suitable for k8s clusters using localPv
Please refer to the README, first create storageClass and pv, then use this chart

A Helm chart for three-nodes zookeeper cluster

---

submitted/reservation-server/.helmignore
submitted/reservation-server/Chart.lock
submitted/reservation-server/Chart.yaml
submitted/reservation-server/README.md
submitted/reservation-server/templates/NOTES.txt
submitted/reservation-server/templates/_helpers.tpl
submitted/reservation-server/templates/configmap.yaml
submitted/reservation-server/templates/deployment.yaml
submitted/reservation-server/templates/service.yaml
submitted/reservation-server/templates/tests/test-connection.yaml
submitted/reservation-server/values.yaml

add reservation-server chart

---

submitted/confluence/Chart.yaml
submitted/confluence/templates/NOTES.txt
submitted/confluence/templates/_helpers.tpl
submitted/confluence/templates/deployment.yaml
submitted/confluence/templates/ingress.yaml
submitted/confluence/templates/service.yaml
submitted/confluence/values.yaml
submitted/jira/Chart.yaml
submitted/jira/templates/NOTES.txt
submitted/jira/templates/_helpers.tpl
submitted/jira/templates/deployment.yaml
submitted/jira/templates/ingress.yaml
submitted/jira/templates/service.yaml
submitted/jira/values.yaml

upgrade confluence & jira,add ingress

upgrade confluence & jira,add ingress

---

submitted/rainbond-operator/Chart.yaml
submitted/rainbond-operator/crds/rainbond.io_rainbondvolumes_crd.yaml
submitted/rainbond-operator/templates/operator-sts.yaml
submitted/rainbond-operator/values.yaml

[rainbond](#goodrain/rainbond) 5.2.0 已经在 4.17 日正式发布, 随着 rainbond 的发布 [rainbond-operator](#goodrain/rainbond-operator) 也作了相应的更新, 所以需要同步一下 cloudnativeapp 里 rainbond-operator 的 charts 包.

update to 1.0.0

---

submitted/milvus/Chart.yaml
submitted/milvus/LICENSE
submitted/milvus/OWMERS
submitted/milvus/README.md
submitted/milvus/ci/db_backend/mysql_cpu_values.yaml
submitted/milvus/ci/db_backend/mysql_gpu_values.yaml
submitted/milvus/ci/db_backend/sqlite_cpu_values.yaml
submitted/milvus/ci/db_backend/sqlite_gpu_values.yaml
submitted/milvus/ci/filebeat/values.yaml
submitted/milvus/requirements.lock
submitted/milvus/requirements.yaml
submitted/milvus/templates/NOTES.txt
submitted/milvus/templates/_helpers.tpl
submitted/milvus/templates/_mishards_config.tpl
submitted/milvus/templates/_readonly_server_config.tpl
submitted/milvus/templates/_server_config.tpl
submitted/milvus/templates/admin-deployment.yaml
submitted/milvus/templates/admin-svc.yaml
submitted/milvus/templates/config.yaml
submitted/milvus/templates/mishards-deployment.yaml
submitted/milvus/templates/mishards-svc.yaml
submitted/milvus/templates/pvc.yaml
submitted/milvus/templates/readonly-deployment.yaml
submitted/milvus/templates/readonly-svc.yaml
submitted/milvus/templates/writable-deployment.yaml
submitted/milvus/templates/writable-svc.yaml
submitted/milvus/values.yaml

Signed-off-by: quicksilver <zhifeng.zhang@zilliz.com>
Add Milvus chart to https://developer.aliyun.com/hub

Add Milvus chart

---

docs/README.md
docs/curated/index.yaml
docs/submitted/index.yaml

add readme
